#数据源
spring:
  mvc:
    static-path-pattern: /static/**
  datasource:
    username: root
    password: ch5201314
    url: jdbc:mysql://localhost:3306/warehouse?useUincode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    initialSize: 5
    minIdle: 5
    maxActive: 20
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    filters: stat,wall,log4j
    maxPoolPreparedStatementPerConnectionSize: 20
    useGlobalDataSourceStat: true
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500
 #关闭缓存,既时刷新
  thymeleaf:
    cache: true
  freemarker:
    cache: false
#热部署生效
  devtools:
    restart:
      enabled: true
      additional-paths: src/mian/java
      exclude: static/**
#配置mybatisplus
mybatis-plus:
  type-aliases-package: com.ch.warehouse.entity
  #xml扫描，多个目录用逗号或者分号分割（告诉 Mapper 所对应的 XML 文件位置）
  mapper-locations: classpath*:/com/ch/warehouse/mapper/*.xml
  global-config:
    db-config:
      #id类型: 0  # 0:数据库ID自增   1:用户输入id  2:全局唯一id(IdWorker)  3:全局唯一ID(uuid)
      id-type: auto
  configuration:
      log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
server:
  port: 8081

